name: Java CI with Gradle

on: [push, pull_request]

permissions:
  contents: read

env:
  API_KEY: "${{ secrets.API_KEY }}"
  GITHUB_ACTOR: "${{ secrets.PACKAGE_ACTOR }}"
  GITHUB_TOKEN: "${{ secrets.PACKAGE_TOKEN }}"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

    - name: Start test
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: test

    - name: Google Java Format
      uses: axel-op/googlejavaformat-action@v3.6.0

    - name: Create Jacoco report
      run: gradle jacocoTestReport

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
